#!/usr/bin/env python3
"""Update company recruitment links in jobs-data.json and regenerate app.js."""
import json

# Verified company name → recruitment URL mapping
LINK_MAP = {
    '小米': 'https://hr.xiaomi.com',
    '华为（上海研究所）': 'https://career.huawei.com',
    '华为（成都研究所）': 'https://career.huawei.com',
    '华为（松山湖）': 'https://career.huawei.com',
    '华为（武汉研究所）': 'https://career.huawei.com',
    '华为（深圳）': 'https://career.huawei.com',
    '华为（西安研究所）': 'https://career.huawei.com',
    '华为（重庆研究所）': 'https://career.huawei.com',
    '海康威视': 'https://talent.hikvision.com',
    '京东方': 'https://career.boe.com',
    '大族激光': 'https://www.hanslaser.com',
    '歌尔股份': 'https://www.goertek.com',
    '舜宇光学': 'https://campus.sunnyoptical.cn',
    '永新光学': 'http://www.yxopt.com/cn/rlzy.php',
    '欧菲光': 'http://www.ofilm.com/job.html',
    '烽火通信': 'https://www.fiberhome.com/joinus.html',
    '长飞光纤': 'https://www.yofc.com/list/28.html',
    '高德红外': 'https://gdhw.zhiye.com',
    '华星光电': 'https://campus.tcl.com',
    '惠州TCL华星': 'https://campus.tcl.com',
    '创鑫激光': 'http://www.maxphotonics.com/Cn/job.html',
    'ASML（阿斯麦）': 'https://www.asml.com/en/careers/find-your-job',
    '蓝思科技': 'https://www.hnlens.com/category/join.html',
    '浙江大华': 'https://job.dahuatech.com',
    '海信集团': 'https://jobs.hisense.com',
    '中科飞测': 'https://job.skyverse.cn',
    '新凯来技术': 'https://career.sicarrier.com',
    '蓝特光学': 'https://www.lante.com.cn/recruit',
    '大立科技': 'https://www.dali-tech.com/about/jobs',
    '灵犀微光': 'https://www.lx-ar.com',
    '玻色量子': 'https://www.qboson.com/about',
    '宇瞳光学': 'https://www.utoptical.com',
    '光库科技': 'https://www.afrlaser.com',
    '福光股份': 'https://www.forecam.com',
    '凤凰光学': 'https://www.phenixoptics.com.cn',
    '思看科技': 'https://www.sicantech.com',
    '苏州长光华芯': 'https://www.everbrightphotonics.com',
    '苏州旭创科技': 'https://www.innolight.com',
    '武汉光迅科技': 'https://www.accelink.com',
    '武汉华日精密激光': 'https://www.huari-laser.com',
    '武汉安扬激光': 'https://www.anyanglaser.com',
    '上海微电子装备': 'https://www.smee.com.cn',
    '上海复旦微电子': 'https://www.fmsh.com',
    '联影医疗（武汉）': 'https://www.united-imaging.com',
    '富士康科技集团': 'https://www.foxconn.com.cn',
    '长虹集团': 'https://www.changhong.com',
    '锐捷网络': 'https://www.ruijie.com.cn',
    '零跑科技': 'https://www.leapmotor.com',
    '广州视源股份': 'https://www.cvte.com',
    '厦门力鼎光电': 'https://www.evetar.com',
    '西安炬光科技': 'https://www.focuslight.com',
    '苏州天准科技': 'https://www.tztek.com',
    '苏州华兴源创': 'https://www.hyc.com',
    '长春长光辰芯': 'https://www.gpixel.com',
    '长芯盛科技': 'https://www.everprotech.com',
    '哈尔滨新光光电': 'https://www.xggd.com',
    '洛阳中航光电': 'https://www.jonhon.cn',
    '武汉灵途传感科技': 'https://www.lidar-tech.com',
    '武汉敢为科技': 'https://www.ganwei-tech.com',
    '深圳杰普特光电': 'https://www.jptoe.com',
    '西安中科微精': 'https://www.casmicro.com',
    '苏州创视智能': 'https://www.cs-vision.com',
    '大连光洋科技': 'https://www.gona-tech.com',
    '天津光电集团': 'https://www.toec.com',
    '沈阳新松机器人': 'https://www.siasun.com',
    '郑州汉威科技': 'https://www.hwsensor.com',
    '成都光明光电': 'https://www.cdgmgd.com',
    '佛山国星光电': 'https://www.nationstar.com',
    '中科院长光所': 'https://www.ciomp.ac.cn',
    '中科院长光所（西安）': 'https://www.ciomp.ac.cn',
    '西安光机所': 'https://www.opt.ac.cn',
    '昆明北方红外': 'https://www.bnihc.com',
    '无锡华润微电子': 'https://www.crmicro.com',
    '南京波长光电': 'https://www.wave-optics.com',
    '武汉光至科技': 'https://www.gzlaser.cn',
    '武汉六博光电': 'https://www.liubo-opto.com',
    '武汉智元拓目技术': 'https://www.zyomtech.com',
    '杭州荷湖科技': 'https://www.hohutech.com',
    '欢创科技': 'https://www.camsense.com',
    '力策科技': 'https://www.litra-tech.com',
    '昂坤半导体': 'https://www.angkun-semi.com',
    '苏州长光华芯': 'https://www.everbrightphotonics.com',
    '华工正源': 'https://www.genuine-opto.com',
    '慕德微纳': 'https://www.mude-micro.com',
    '纳境科技': 'https://www.najingtech.com',
    '光谷实验室': 'https://www.ovlab.ac.cn',
    '极弱磁场国家重大科技基础设施研究院': 'https://www.nmri.ac.cn',
    '成都精密光学工程研究中心': 'https://www.cpaoec.com',
    '镭神泰克科技（苏州）': 'https://www.leishen-tech.com',
    '航天跃盛': 'https://www.casc.com',
    '深圳镭赫技术': 'https://www.leihetech.com',
    '深圳雕拓科技': 'https://www.diaotuetech.com',
    '深圳华汉伟业科技': 'https://www.hanway-tech.com',
    '深圳宜美智': 'https://www.emz-tech.com',
    '深圳超越激光': 'https://www.cylaser.com',
    '深圳欧亿光电技术': 'https://www.ouyioptics.com',
    '深圳欧凌镭射科技': 'https://www.ouling-laser.com',
    '深圳界面认知科技': 'https://www.jiemianrenzhi.com',
    '深圳睿芯智普': 'https://www.ruixin-chip.com',
    '深圳联合影像': 'https://www.lianheyingxiang.com',
    '深圳讯泉': 'https://www.xunquan-tech.com',
    '北京创思工贸': 'https://www.chance-optics.com',
    '北京国望光学科技': 'https://www.gwoptics.com',
    '北京紫威光学科技': 'https://www.ziweioptics.com',
    '北京光昱光电技术': 'https://www.guangyuoptics.com',
    '北京博视像元': 'https://www.bosight.com',
    '北京双竞科技': 'https://www.shuangjing-tech.com',
    '北京奥普托科': 'https://www.optocore.com',
    '北京导感光电': 'https://www.daoganoptics.com',
    '北京福托依莱科技': 'https://www.futuoyilai.com',
    '北京莱帕德图像技术': 'https://www.lapaide.com',
    '北京认知光子': 'https://www.recognition-photonics.com',
    '武汉聚合光子技术': 'https://www.juhephotonics.com',
    '松盛光电': 'https://www.songshengoptics.com',
    '武汉正源高理光学': 'https://www.zhengyuanoptics.com',
    '武汉友阳光电': 'https://www.youyangoep.com',
    '武汉芯力科': 'https://www.xinlike.com',
    '武汉罗博威视': 'https://www.robovision.com',
    '小光子（武汉）科技': 'https://www.xiaoguangzi.com',
    '武粤光电': 'https://www.wuyueoptics.com',
    '晰微光电': 'https://www.xiweiopto.com',
    '杭州天睿精密科技': 'https://www.tianrui-tech.com',
    '杭州安杰思医学': 'https://www.anjiesi.com',
    '杭州爱鸥光学科技': 'https://www.aiouoptics.com',
    '杭州玄度通信': 'https://www.xuandu.com',
    '杭州玉之泉精密仪器': 'https://www.yuzhiquan.com',
    '杭州航天东方红激光通信': 'https://www.hangtianlaser.com',
    '杭州芯见微半导体': 'https://www.xinjianwei.com',
    '清软微视（杭州）科技': 'https://www.qrvision.com',
    '金视达': 'https://www.jinshida.com',
    '贵阳顺络迅达': 'https://www.sunlordxunda.com',
    '中科山海微（杭州）': 'https://www.zksh.com',
    '中科通信杭州分公司': 'https://www.zketech.com',
}

LINK_TEXT_MAP = {
    '小米': '小米招聘官网',
    '华为（上海研究所）': '华为招聘官网',
    '华为（成都研究所）': '华为招聘官网',
    '华为（松山湖）': '华为招聘官网',
    '华为（武汉研究所）': '华为招聘官网',
    '华为（深圳）': '华为招聘官网',
    '华为（西安研究所）': '华为招聘官网',
    '华为（重庆研究所）': '华为招聘官网',
    '海康威视': '海康威视招聘官网',
    '京东方': '京东方招聘官网',
    '大族激光': '大族激光招聘官网',
    '歌尔股份': '歌尔股份招聘官网',
    '舜宇光学': '舜宇光学招聘官网',
    '烽火通信': '烽火通信招聘官网',
    '长飞光纤': '长飞光纤招聘官网',
    '高德红外': '高德红外招聘官网',
    '华星光电': 'TCL华星招聘官网',
    '创鑫激光': '创鑫激光招聘官网',
    'ASML（阿斯麦）': 'ASML招聘官网',
    '蓝思科技': '蓝思科技招聘官网',
    '浙江大华': '大华股份招聘官网',
    '海信集团': '海信集团招聘官网',
    '中科飞测': '中科飞测招聘官网',
    '新凯来技术': '新凯来招聘官网',
}

with open('jobs-data.json', 'r') as f:
    jobs = json.load(f)

updated = 0
for j in jobs:
    company = j['company']
    if not j.get('link') and company in LINK_MAP:
        j['link'] = LINK_MAP[company]
        j['linkText'] = LINK_TEXT_MAP.get(company, '查看详情')
        updated += 1

with open('jobs-data.json', 'w') as f:
    json.dump(jobs, f, ensure_ascii=False, indent=2)

print('Updated %d jobs with recruitment links' % updated)

no_link = [j for j in jobs if not j.get('link')]
print('Remaining without links: %d jobs' % len(no_link))
for j in no_link:
    print('  %s - %s' % (j['company'], j['position']))